[openscadgen]
name = "catan_holder_pieces"
description = ""

version = "v0.1"

export_name_format = "{designFileName}_{renderType}_{dovetailType}_{name}"


[[openscadgen.input_paths]]
path = "./catan_holder_pieces.scad"


[[openscadgen.instances]]
name = "hex"
description = ""
params = { renderType = "hex" }


[[openscadgen.instances]]
name = "port"
description = ""
params = { renderType = "port", dovetailType = "male,female"}


[[openscadgen.instances]]
name = "port-offset"
description = ""
params = { renderType = "port-offset", dovetailType ="male,female" }

[[openscadgen.instances]]
name = "port-reversed"
description = ""
params = { renderType = "port-offset-reversed", dovetailType ="male,female" }

[[openscadgen.images]]
name = "nice"