[openscadgen]
name = "carovan-cupboard-hook"
description = """\
 A simple model that creates a cupboard hook.


"""

export_name_format = "{designFileName}-{hook_count}-{hook_angle}"


version = "v0.2"

[[openscadgen.input_paths]]
path = "./carovan-cupboard-hook-v2.scad"

[[openscadgen.instances]]
params = { hook_count = "1", hook_angle = "40, 50, 70"}