[openscadgen]
name = "carovan-cupboard-hook"
description = """\
 A simple model that creates a cupboard hook.


"""

export_name_format = "export/{designFileName}-{height}-{hook_count}"


version = "v0.1"

[[openscadgen.input_paths]]
path = "./carovan-cupboard-hook-v2..scad"

[[openscadgen.instances]]
params = { hook_count = "1,3,5,7,10,15,20,30", hook_angle = "40, 50, 70"}