[openscadgen]
name = "carovan-cupboard-hook"
description = """\
 A simple model that creates a cupboard hook.


"""

export_name_format = "{designFileName}-{height}"


version = "v0.4"

[[openscadgen.input_paths]]
path = "./carovan-cupboard-hook-v2.scad"

[[openscadgen.instances]]
params = { hook_angle = 40, height = [10, 50, 90]}