[openscadgen]
name = "furniture_foot"
description = ""

version = "v0.1"

export_name_format = "/{designFileName}"

# export_name_format = "custom-export-name-for-this-file/{designFileName}-{instanceName}"

[[openscadgen.input_paths]]
path = "./furniture_foot.scad"

# [[openscadgen.input_paths]]
# path = "./a-second-related-openscad-file.scad"

# [[openscadgen.instances]]
# params = {renderType = "horzSlice,vertSlice", param1 = "a-custom-value" }

# [[openscadgen.instances]]
# params = { renderType = "horzSlice,vertSlice", param1 = "a-diff-custom-value" }
