# Update the version to 2
version: 2

project_name: openscadgen

builds:
  - main: ./main.go
    binary: openscadgen
    goos:
        - linux
        - darwin
        - windows
    goarch:
      - amd64
      - arm64
    ldflags:
        - -s -w

archives:
  - formats: [ 'zip' ]
    name_template: "{{ .ProjectName }}-{{ if eq .Os \"darwin\" }}{{ if eq .Arch \"amd64\" }}macOS-Intel{{ else }}macOS-AppleSilicon{{ end }}{{ else if eq .Os \"windows\" }}Windows-{{ .Arch | title }}{{ else if eq .Os \"linux\" }}Linux-{{ .Arch | title }}{{ end }}-v{{ .Version }}"
    files:
      - README.md
      - INSTALL.md
      - examples/**
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

release:
  github:
    owner: kiwikid
    name: openscadgen
  name_template: 'v{{ .Version }}'