[openscadgen]
name = "match_handle"
description = ""

version = "v0.1"

export_name_format = "{designFileName}"

[[openscadgen.input_paths]]
path = "./match_handle.scad"

[[openscadgen.images]]
name = "nice"
