[openscadgen]
name = "any_cup"
description = ""

version = "v0.1"

export_name_format = "{designFileName}_{renderType}"

global_params = { renderType = "obj,vertSlice,horzSlice,all" }

[[openscadgen.input_paths]]
path = "./any_cup.scad"

[[openscadgen.images]]
name = "nice"
