[openscadgen]
name = "football_cards"
description = ""

version = "v0.2"

export_name_format = "{designFileName}/{type}/{initals}"

global_params = { initals = "GC,ML,JC,NM,CC,NH,TW,JG", type = "insert,normal" }

[[openscadgen.images]]
name = "nice"

[[openscadgen.images]]
name = "top"

[[openscadgen.input_paths]]
path = "./football_cards.scad"


