# These lines configure, where the config file is, how openscad will be run and where the output will be saved
[openscadgen]
name = "washing-machine-seal"
description = """\
 A simple model that creates a washing machine seal.

 Three render options are available:
 - horz-slice: A horizontal slice of the cup holder
 - vert-slice: A vertical slice of the cup holder
 - all: All three views of the cup holder

The coaster is designed to be printed on a flat surface, with the text on the outside edge of the coaster.

"""

export_name_format = "{designFileName}_extrude_{renderType}"

output_path = "./export/"
version = "v0.1"

[[openscadgen.input_paths]]
path = "./washing-machine-seal.scad"

[[openscadgen.instances]]
params = { renderType = "horz-slice,vert-slice,all"}
