# These lines configure, where the config file is, how openscad will be run and where the output will be saved
[openscadgen]
name = "coffee-cup-holder"
description = """\
 A simple model that creates a coffee cup holder.

 Three render options are available:
 - horz-slice: A horizontal slice of the cup holder
 - vert-slice: A vertical slice of the cup holder
 - all: All three views of the cup holder

The coaster is designed to be printed on a flat surface, with the text on the outside edge of the coaster.

"""

export_name_format = "/{designFileName}_extrude_{renderType}"


version = "v0.1"

[[openscadgen.input_paths]]
path = "./coffee-cup-holder-v2.scad"

[[openscadgen.instances]]
params = { renderType = "horz-slice,vert-slice"}
