[openscadgen]
name = "wheel_ticker"
description = ""

version = "v0.1"

export_name_format = "{designFileName}_{obj}"

global_params = { obj = "all,ticker,holder" }

[[openscadgen.input_paths]]
path = "./wheel_ticker.scad"

[[openscadgen.images]]
name = "nice"
param_filter = { renderType= "obj,vertSlice,horzSlice"}
