[openscadgen]
name = "can_tip_preventer"
description = ""

version = "v0.1"

export_name_format = "{designFileName}"

global_params = { }

[[openscadgen.input_paths]]
path = "./can_tip_preventer.scad"
params = { }

[[openscadgen.images]]
name = "nice"
