[openscadgen]
name = "tralier-9-pin-connector"
description = """\
 A simple model that creates a 9 pin connector.


"""

export_name_format = "/{designFileName}"


version = "v0.1"

[[openscadgen.input_paths]]
path = "./tralier-9-pin-connector.scad"

[[openscadgen.instances]]
