[openscadgen]
name = "rav4_phone_holder"
description = ""

version = "v0.1"

export_name_format = "{designFileName}_{bottomShelf}"

global_params = { renderType = "obj", bottomShelf = "includeBottomShelf,noBottomShelf" }

[[openscadgen.input_paths]]
path = "./rav4_phone_holder.scad"

[[openscadgen.images]]
name = "nice"
param_filter = { renderType= "obj"}
