[openscadgen]
name = "rounded_button_box"
description = ""

version = "v0.6"



# rowCount=[3,4,5,6,7,8,9,10], colCount = [3,4,5,6,7,8]
global_params = { rowCount=[10], colCount = [3] }

[[openscadgen.input_paths]]
path = "./rounded_button_box.scad"

# [[openscadgen.instances]]
# export_name_format = "{designFileName}/sizing/{section}"
# params = { section = ["devSingleBox", "devTopSample", "devTopCorner",  "all", "buttonJiggleBorder"] }


# "wallMount", "wallMount-withSpace-bottom", "wallMount-withSpace-top", "wallMount-withSpace-all",
[[openscadgen.instances]]
export_name_format = "{designFileName}/row{rowCount}_col{colCount}/{section}"  
params = { section=["buttonJiggleBorder", "top", "bottom",  "all", "cordPlugBottom", "cordPlugSide", "cordPlugNoHolesSide", "cordPlugNoHolesBottom"] }


[[openscadgen.instances]]
export_name_format = "{designFileName}/row{rowCount}_col{colCount}/{section}-{wallMountMode}"
params = { section = ["wallMount"], wallMountMode=["wmTop", "wmBottom"] }

# export_name_format = "{designFileName}/sizing/{section}" withSpaceExtraSpace = 600;
# params = { section = ["devSingleBox", "devTopSample", "devTopCorner",  "all", "buttonJiggleBorder"] }



[[openscadgen.images]]
name = "nice"
type = "all_instances"
coord = "0,0,0,45,0,45,1000"

[[openscadgen.images]]
name = "back"
param_filter = { section= "all"}
