[openscadgen]
name = "cube"
description = ""

version = "v0.1"

export_name_format = "/{version}/{designFileName}-{instance}-{cube_center}-{cube_size}"

[[openscadgen.input_paths]]
path = "./cube.scad"


[[openscadgen.images]]
name = "nice"

[[openscadgen.instances]]
params = { cube_size = 50, cube_center = true, instance = "small" }

[[openscadgen.instances]]
params = { cube_size = 50, cube_center = false, instance = "medium" }

[[openscadgen.instances]]
params = { cube_size = 50, cube_center = true, instance = "chamfer", chamfer=3 }

