[openscadgen]
name = "regular_prism"
description = ""

version = "v0.1"

export_name_format = "/{version}/{designFileName}-n{regular_prism_n}-h{regular_prism_h}-r{regular_prism_r}"

[[openscadgen.input_paths]]
path = "./regular_prism.scad"

[[openscadgen.images]]
name = "nice"

[[openscadgen.instances]]
params = { regular_prism_n = 5, regular_prism_h = 25, regular_prism_r = 10 }

[[openscadgen.instances]]
params = { regular_prism_n = 6, regular_prism_h = 40, regular_prism_r = 15, regular_prism_rounding = 5 }

[[openscadgen.instances]]
params = { regular_prism_n = 3, regular_prism_h = 60, regular_prism_r = 20, regular_prism_rounding = 10 }

