[openscadgen]
name = "hand-press-plate"
description = ""

version = "v0.1"

export_name_format = "/{designFileName}-{renderType}-{plateType}-{attachCyliderHeight}-{plateHeight}"

#global_params = { renderType = "", plateType = "large,none" }

[[openscadgen.input_paths]]
path = "./hand-press-plate.scad"

[[openscadgen.instances]]
params = {  plateType = "large", attachCyliderHeight = 25, plateHeight = [30,35,40,45,50] }

[[openscadgen.instances]]
params = { plateType = "none", attachCyliderHeight = 25  }



[[openscadgen.images]]
name = "top"

[[openscadgen.images]]
name = "left"


# [[openscadgen.input_paths]]
# path = "./a-second-related-openscad-file.scad"
# ignore_param_when_processing = "param3" # dont process param3 when generating instances for this file 

# [[openscadgen.instances]]
# params = {renderType = "horzSlice,vertSlice,all", param1 = "a-custom-value" }

# [[openscadgen.instances]]
# params = { renderType = "horzSlice,vertSlice,all", param1 = "a-diff-custom-value" }
