[openscadgen]
name = "phone_holder"
description = ""

version = "v0.1"

export_name_format = "{designFileName}_{renderType}"

global_params = { renderType = "obj,vertSlice,horzSlice,all" }

[[openscadgen.input_paths]]
path = "./phone_holder.scad"

[[openscadgen.images]]
name = "nice"
