# These lines configure, where the config file is, how openscad will be run and where the output will be saved
[openscadgen]
# name of the design, will be used in the name of output files
name = "screw-mounted-clip"
# description of the design, will be used in the README.md file
description = "A parametric screw mounted clip"
# path to the openscad file that will be used to generate the design
input_path = "./examples/screw-mounted-clip/parametricCommandStripBroomHook.scad"
# path to the directory where the export (.stl files, README.md) will be saved
output_path = "./examples/screw-mounted-clip/export/"
# version of the design, will be used in the README.md file
version = "v1.6"
# Each instance below will result in a separate .stl file being created with those parameters in the 'output_path' directory


# Dynamic Instances

[[openscadgen.dynamic_instances]]
# The 'name' field is a template string that will be used to generate the instance name (note the {param_name} syntax for value replacement)
name = "clip-{handle_diameter}mm-wide-{handle_offset}mm-tall"
# the params field configures which instances get created ()
params = { handle_diameter = "5,7,8,10,15,20,25,30", handle_offset = "5,10,15,20,25,30" }


# Specific models

[[openscadgen.instances]]
name = "clip-for-large-ended-hex-tool"
description = "A clip sized for a hex tool with a large piece"
[openscadgen.instances.params]
handle_diameter = 7
handle_offset = 15
