[openscadgen]
name = "small-tray"
description = ""


version = "v0.1"

export_name_format = "{designFileName}-{instanceName}-{partType}"
global_params = { partType = "box" }

[[openscadgen.input_paths]]
path = "./small-tray.scad"

[[openscadgen.instances]]
name = "small-tray"
params = { tray_width = 48, tray_height = 52, height = 30 }

[[openscadgen.instances]]
name = "large-tray-35"
params = {  tray_width = 230, tray_height = 250, height = 35 }
 
[[openscadgen.instances]]
name = "large-tray-50"
params = {  tray_width = 230, tray_height = 250, height = 50 }
 
[[openscadgen.instances]]
name = "large-tray-100"
params = {  tray_width = 230, tray_height = 250, height = 100 }

[[openscadgen.instances]]
name = "test-command-output"
params = {  tray_width = 50, tray_height = 50, height = 20 }

[[openscadgen.images]]
name = "front"
coord = "0,0,0,0,0,0,100"
