[openscadgen]
name = "small-tray"
description = ""


version = "v0.1"

export_name_format = "export/{designFileName}-{instanceName}-{partType}"
global_params = { partType = "box,startBox,endBox" }

[[openscadgen.input_paths]]
path = "./small-tray.scad"

[[openscadgen.instances]]
name = "small-tray"
params = { tray_width = 46, tray_height = 50, height = 28 }

[[openscadgen.instances]]
name = "large-tray-35"
params = {  tray_width = 230, tray_height = 250, height = 35 }
 
[[openscadgen.instances]]
name = "large-tray-50"
params = {  tray_width = 230, tray_height = 250, height = 50 }
 
[[openscadgen.instances]]
name = "large-tray-100"
params = {  tray_width = 230, tray_height = 250, height = 100 }

[[openscadgen.instances.export_images]]
name = "front"
