[openscadgen]
name = "hinge_hanging"
description = ""

version = "v0.1"

export_name_format = "{designFileName}_{width}"

global_params = { width=[10,30,50] }

[[openscadgen.input_paths]]
path = "./hinge_hanging.scad"

[[openscadgen.images]]
name = "nice"
