# These lines configure, where the config file is, how openscad will be run and where the output will be saved
[openscadgen]
name = "shopping_list_v3"
description = """\
 A simple model that creates a shopping list.


"""

export_name_format = "{designFileName}"

output_path = "./export/"
version = "v0.1"

[[openscadgen.input_paths]]
path = "./shopping_list_v3.scad"

[[openscadgen.instances]]