[openscadgen]
name = "cuboid"
description = ""

version = "v0.1"

export_name_format = "/{version}/{designFileName}-size{cuboid_size[0]}x{cuboid_size[1]}x{cuboid_size[2]}-chamfer{cuboid_chamfer}-rounding{cuboid_rounding}"

[[openscadgen.input_paths]]
path = "./cuboid.scad"

[[openscadgen.images]]
name = "nice"

[[openscadgen.instances]]
params = { cuboid_size = [100,100,100], cuboid_chamfer = 0, cuboid_rounding = 0 }

[[openscadgen.instances]]
params = { cuboid_size = [80,120,60], cuboid_chamfer = 10, cuboid_rounding = 0 }

[[openscadgen.instances]]
params = { cuboid_size = [60,60,60], cuboid_chamfer = 0, cuboid_rounding = 15, cuboid_trimcorners = false }

