[openscadgen]
name = "cube-rectangular"
description = "Rectangular 50x150x80 cube not centered"

version = "v0.1"

export_name_format = "/{version}/{designFileName}_{cube_size}"

[[openscadgen.input_paths]]
path = "./cube-rectangular.scad"

[[openscadgen.images]]
name = "nice"

[[openscadgen.instances]]
params = { cube_size = 50, cube_center = false } 