[openscadgen]
name = "ball_bearing_mount"
description = ""

version = "v0.1"

export_name_format = "{designFileName}_{renderType}"

global_params = { renderType = "obj,vertSlice,horzSlice" }

[[openscadgen.input_paths]]
path = "./ball_bearing_mount.scad"

[[openscadgen.images]]
name = "nice"
param_filter = { renderType= "obj,vertSlice,horzSlice"}
