# These lines configure, where the config file is, how openscad will be run and where the output will be saved
[openscadgen]
name = "insta-360-x2-case-for-large-cord"
description = "A case for the Insta360 X2 camera"
output_path = "./examples/insta-360-x2-case-for-large-cord/export"
version = "v0.2"
custom_openscad_args = "--summary"
no_part_id_letter = true
[[openscadgen.input_paths]]
path = "./examples/insta-360-x2-case-for-large-cord/insta360x2-case.scad"
[[openscadgen.input_paths]]
path = "./examples/insta-360-x2-case-for-large-cord/insta360x2-top.scad"
#[[openscadgen.input_paths]]
#path = "./examples/insta-360-x2-case-for-large-cord/insta360x2-cap.scad"

[[openscadgen.dynamic_instances]]
# The 'name' field is a template string that will be used to generate the instance name (note the {param_name} syntax for value replacement)
# the params field configures which instances get created ()
name = "includeGoProMount-{includeGoProMount}/cylinderWidth-{cylinderWidth}/{designFileName}"
params = { cylinderWidth = "3,3.5", includeGoProMount = "true,false" }

