[openscadgen]
name = "coffee_holder_tray"
description = ""

version = "v0.1"

export_name_format = "{designFileName}"

global_params = { }

[[openscadgen.input_paths]]
path = "./coffee_holder_tray.scad"
params = { }

[[openscadgen.images]]
name = "nice"
