[openscadgen]
name = "prismoid"
description = ""

version = "v0.1"

export_name_format = "/{version}/{designFileName}-size1{prismoid_size1[0]}x{prismoid_size1[1]}-size2{prismoid_size2[0]}x{prismoid_size2[1]}-h{prismoid_h}"

[[openscadgen.input_paths]]
path = "./prismoid.scad"

[[openscadgen.images]]
name = "nice"

[[openscadgen.instances]]
params = { prismoid_size1 = [35,50], prismoid_size2 = [20,30], prismoid_h = 20 }

[[openscadgen.instances]]
params = { prismoid_size1 = [60,40], prismoid_size2 = [10,10], prismoid_h = 40, prismoid_rounding = 8 }

[[openscadgen.instances]]
params = { prismoid_size1 = [100,40], prismoid_size2 = [40,10], prismoid_h = 30, prismoid_chamfer = 5 }

