[openscadgen]
name = "zero_chair_trophy"
description = ""

version = "v0.1"

export_name_format = "{designFileName}"

global_params = { }

[[openscadgen.input_paths]]
path = "./zero_chair_trophy.scad"
params = { }

[[openscadgen.images]]
name = "nice"
