[openscadgen]
name = "cube-basic"
description = "Basic 100x100x100 cube centered"

version = "v0.1"

export_name_format = "/{version}/{designFileName}_{cube_size}_{round}"

[[openscadgen.input_paths]]
path = "./cube-basic.scad"

[[openscadgen.images]]
name = "nice"

[[openscadgen.instances]]
params = { cube_size = [50,75,100], round=[0, 3], cube_center = true } 