[openscadgen]
name = "washing-machine-seal-v3"
description = ""

version = "v0.1"

export_name_format = "{designFileName}-{renderType}"

# export_name_format = "custom-export-name-for-this-file/{designFileName}-{name}"

[[openscadgen.input_paths]]
path = "./washing-machine-seal-v3.scad"

[[openscadgen.instances]]
params = {renderType = "horzSlice,vertSlice,seal" }

# [[openscadgen.input_paths]]
# path = "./a-second-related-openscad-file.scad"

# [[openscadgen.instances]]
# params = {renderType = "horzSlice,vertSlice,all", param1 = "a-custom-value" }

# [[openscadgen.instances]]
# params = { renderType = "horzSlice,vertSlice,all", param1 = "a-diff-custom-value" }
