[openscadgen]
name = "bolt_sizer"
description = ""

version = "v0.1"

export_name_format = "{designFileName}_{mode}"

global_params = { }

[[openscadgen.input_paths]]
path = "./bolt_sizer.scad"


[[openscadgen.instances]]
params = { mode = "box,text,bottomRender,bottomRenderBox,logo,glueJig,glueJoinerSquare" }

[[openscadgen.images]]
name = "nice"
